[build-system]
requires = ["setuptools>=57", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
skip-string-normalization = true
target-version = ["py39"]
include = ".*[.]py$"
exclude = "env"
line-length = 100
